name: DotNet Build & Sonar Analysis
description: Build .NET project, run Coverlet for test coverage, and SonarQube analysis

inputs:
  dotnet-version:
    description: ".NET version to use"
    required: true
  sln-path:
    description: "Path to the .sln file to build (e.g., src/MyApp.sln)"
    required: true
  test-project-path:
    description: "Path to the test project (.csproj) to run (e.g., test/WMS.UnitTest/WMS.UnitTest.csproj)"
    required: true
  test-report-path:
    description: "Path to the test results file (e.g., UnitTest/coverage.opencover.xml)"
    required: false
  sonar-project-key:
    description: "SonarQube project key"
    required: true
  sonar-tags:
    description: "Comma-separated list of required tags (e.g. projectname=myapp,owner=Manish)"
    required: true
  test-exclusions:
    description: "Comma-separated list of test case paths to exclude"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Validate tags
      shell: bash
      run: |
        echo "🔍 Validating tags..."
        required_keys=("projectname" "owner")

        # Split tags by comma
        IFS=',' read -ra TAGS <<< "${{ inputs.sonar-tags }}"

        for key in "${required_keys[@]}"; do
          found=false
          for tag in "${TAGS[@]}"; do
            if [[ "$tag" == $key=* ]]; then
              value="${tag#*=}"
              if [[ -z "$value" ]]; then
                echo "❌ Tag $key has no value!"
                exit 1
              fi
              echo "✅ Found required tag: $key=$value"
              found=true
              break
            fi
          done
          if [ "$found" = false ]; then
            echo "❌ Missing required tag: $key"
            exit 1
          fi
        done

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install OpenSSL 1.1
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.1/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb

    - name: Install dependencies
      shell: bash
      run: dotnet restore "${{ inputs.sln-path }}"

    - name: Build
      shell: bash
      run: dotnet build "${{ inputs.sln-path }}" --no-restore --configuration Release

    - name: Run tests with coverage
      shell: bash
      run: |
        dotnet test "${{ inputs.test-project-path }}" --no-build --configuration Release \
          /p:CollectCoverage=true \
          /p:CoverletOutput=TestResults/ \
          /p:CoverletOutputFormat=opencover \
          /p:Exclude="[${{ inputs.test-exclusions }}]*"

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2
      env:
        SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=${{ inputs.sonar-project-key }}
          -Dsonar.cs.opencover.reportsPaths=${{ inputs.test-report-path }}
          -Dsonar.taglist=${{ inputs.sonar-tags }}
